### ISSUE TITLE
Deprecated: Implicit conversion from float 4995090.007781982 to int loses precision in vendor\react\event-loop\React\EventLoop\StreamSelectLoop.php on line 137

### ISSUE THREAD

**Issue by RobertEcker** [reactphp/event-loop#253] opened 2022-05-15 19:40 UTC
Reason: https://php.watch/versions/8.1/deprecate-implicit-conversion-incompatible-float-string

I am using PHP 8.1.2 (cli) (built: Jan 19 2022 10:18:23) (ZTS Visual C++ 2019 x64)

PS: Thank you for reactphp ;-)

**Comment by clue** [comment] 2022-05-15 20:50
@RobertEcker Thank you for reporting. Can you provide more context and/or a gist to reproduce this? You're the first to report this and I currently fail to see how this line would raise a notice:

https://github.com/reactphp/event-loop/blob/1fd1d01c45fcf8764b00a58cc2e35283c5fd5978/src/StreamSelectLoop.php#L137

**Comment by RobertEcker** [comment] 2022-05-15 21:22
@clue Sure:

1. Download https://github.com/reactphp-legacy/whois
2. composer install --ignore-platform-reqs
3. start whois-master\examples\query.php
4. error is shown

Hope you can reproduce it, too

**Comment by clue** [comment] 2022-05-15 21:39
@RobertEcker Looks like the problem comes from using an outdated package, as that package is deprecated more than 4 years ago as per https://github.com/reactphp-legacy/whois/issues/15. Accordingly, this will try to install a somewhat dated version of this EventLoop. Using a current version, I can not reproduce this problem you're seeing (see also the test suite that comes with this project).

I'm not sure how much interest there is for an up-to-date whois package, but I would usually recommend filing this downstream. If there's enough interest, I'm sure this is something that somebody will pick up again.

I hope this helps! I believe this has been answered, so I'm closing this for now. Please come back with more details if this problem persists and we can always reopen this :+1:

**Closed as completed by clue** 2022-05-15 21:39 UTC
Labels: question
