### ISSUE TITLE
addTimer() accepts values that it doesn't support, freezes StremSelectLoop::run()

### ISSUE THREAD

**Issue by arnaud-lb** [reactphp/event-loop#168] opened 2018-06-24 20:44 UTC
When addTimer() receives a $interval parameter that's high enough, a float value is passed to usleep(). The function will reject the value, and return immediately, causing a busy loop.

StremSelectLoop currently does not support intervals higher than PHP_INT_MAX/1000000. This limitation itself is not harmful, however it freezes any program that accidentally sets an interval higher than this.

**Comment by clue** [comment] 2018-06-25 08:11
@arnaud-lb Thank you for reporting!

Unfortunately, I'm currently unable to reproduce the problem you're seeing.

A similar issue has been fixed via https://github.com/reactphp/event-loop/pull/132 a while back and my tests confirm that this should be fixed (the PR also uses a timer interval of `PHP_INT_MAX`).

Is the problem you're seeing reproducible? Can you show a gist that highlights this issue?

**Comment by clue** [comment] 2018-06-28 12:11
I'm closing this for now as it hasn't received any new input and I believe this has been answered. Please come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2018-06-28 12:11 UTC
Labels: help wanted, question

**Comment by arnaud-lb** [comment] 2018-06-28 17:35
Thanks, I confirm that https://github.com/reactphp/event-loop/pull/132 fixed the problem.
