### ISSUE TITLE
ExtEventLoop: All error reporting is suppressed

### ISSUE THREAD

**Issue by mamciek** [reactphp/event-loop#50] opened 2016-05-03 19:31 UTC
Please remove the '@' when using ExtEventLoop. It causes the error_reporting to be set to 0 value and you cannot see ANY errors.

https://github.com/reactphp/react/pull/234#discussion-diff-7759616R226

**Comment by cebe** [comment] 2016-05-04 13:34
Can you be more specific about which error this hides for you?

**Comment by mamciek** [comment] 2016-05-04 18:44
any php notice, warning, error, even fatal errors in code that is executed by event loop - which means almost every subscriber or observable

**Comment by cebe** [comment] 2016-05-06 13:34
okay, sorry now I got it. You link was no directing me to the right place last time I clicked it.

So its about this line: https://github.com/reactphp/event-loop/blob/164799f73175e1c80bba92a220ea35df6ca371dd/src/ExtEventLoop.php#L205

**Comment by mamciek** [comment] 2016-05-06 18:25
yes, it is about line 205 and also https://github.com/reactphp/event-loop/blob/164799f73175e1c80bba92a220ea35df6ca371dd/src/ExtEventLoop.php#L182

**Comment by dustingraham** [comment] 2016-05-07 21:33
Just burned me as well. Using `ExtEventLoop` and I had an example script where it was running `$item->method()->otherMethod();` and mysteriously dying because I had forgot that the `otherMethod` was removed. But I wasn't receiving any errors.

**Comment by clue** [comment] 2017-01-09 08:54
Can anybody file a PR to reproduce and/or fix this? :shipit:

**Comment by mamciek** [comment] 2017-01-09 09:53
https://github.com/reactphp/event-loop/pull/65 - this pull request fixes the problem

**Comment by jsor** [comment] 2017-02-15 20:05
Fixed via #65, will be available in the upcoming v0.4.3 release. Thanks @mamciek 🥇

**Closed** 2017-02-15 20:06 UTC
Labels: bug, easy pick
