### ISSUE TITLE
If tick is called in futureTickQueue we got exception

### ISSUE THREAD

**Issue by nick4fake** [reactphp/event-loop#60] opened 2016-11-16 13:03 UTC
Hi,

On our project we call futureTick() in case in stream handler we need to wait for new data to populate. It has internal call to tick() that eventually clears current futureTick queue. In FutureTickQueue in tick() we simply call dequeue() exact amount of times equal to queue length at the tick() beginning. The problem is that we don't check if queue is already empty.

**Comment by clue** [comment] 2016-11-16 20:37
I'm not sure I follow what you're doing, can you provide a gist to reproduce this?

In case you're calling `tick()` will the loop is running, this is probably where the problem comes from. This should not be done, ever.

**Comment by nick4fake** [comment] 2016-11-18 15:21
@clue Please check this library:
https://github.com/WyriHaximus/reactphp-psr7-stream-converter/blob/master/src/ReactToPSR7Stream.php

Here tick() is called if on read there is no data. If I understand correctly, this is for loop not to block.

I use futureTick to queue read/write pipeline, eg:
````
public function tick()
{
    while (true) {
        $data = $this->input->read(self::BUFFER);
        if ('' === $data) {
            break;
        }

        // TODO: limit write rate
        $this->output->write($data);
    }

    if (!$this->input->eof()) {
        $this->queueTick();
        return;
    }
    $this->input->close();
    $this->output->close();
    call_user_func($this->result);
}

protected function queueTick()
{
    $this->loop->futureTick([$this, 'tick']);
}
````

Is this a correct way to implement PSR7->PSR7 pipeline?

**Comment by nick4fake** [comment] 2016-11-18 17:20
Another example:
https://github.com/WyriHaximus/ReactGuzzle/blob/master/src/HttpClientAdapter.php

What if we make a call inside a loop?

**Comment by clue** [comment] 2016-11-18 18:50
Let's ping @WyriHaximus and let's see what he has to add :+1:

**Comment by WyriHaximus** [comment] 2016-11-18 22:00
@nick4fake it's a horrible hack that I would not recomend :disappointed: , heck I strongly discourage of doing it when there are alternatives. It 'works' but only in most circumstances. That one in particular was made to provide a fully working `PSR-7` stream. @clue made a much better way of doing that [here](https://github.com/clue/php-buzz-react#streaming). Another place I use it is [here](https://github.com/WyriHaximus/react-guzzle-psr7/blob/master/src/HttpClientAdapter.php#L135), but there I'm doing it because Guzzle uses some funky queue that I have to keep running in order for the adapter to work :disappointed: .

**Comment by clue** [comment] 2016-11-19 17:33
@WyriHaximus thanks for giving some insight! What do you suggest we should do here? Is this something worth fixing or should we look into avoiding this altogether (is this even reasonable?)?

**Comment by clue** [comment] 2017-02-08 18:43
I believe this has been superseded now that #72 is in and the `tick()` method has been removed :+1: 

I'm closing this for now, please feel free to come back with more details if this problem persists and we can reopen this :+1:

**Closed by clue** 2017-02-08 18:43 UTC
Labels: question
